# .github/actions/register_test_report/action.yml

name: Register test to report service
description: Register test to report service

inputs:
  title:
    description: "Title of the test"
    required: true
  subtitle:
    description: "Subtitle of the test"
    required: false
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Register test to report service
      shell: bash
      run: |
        BASE_URL="https://report.rt.dnotitia.ai/github/test_job"
        METHOD="POST"
        RUN_ID="${{ github.run_id }}"
        JOB_ID="${{ github.job }}"
        REPO_NAME="${{ github.repository }}"
        BRANCH="${{ github.ref_name }}"

        TITLE="${{ inputs.title }}"
        SUBTITLE="${{ inputs.subtitle }}"
        TOKEN="${{ inputs.github_token }}"

        BODY="{\"run_id\": \"$RUN_ID\", \"job_id\": \"$JOB_ID\", \"repo_name\": \"$REPO_NAME\", \"head_branch\": \"$BRANCH\", \"title\": \"$TITLE\", \"subtitle\": \"$SUBTITLE\"}"

        RESPONSE=$(curl -X "$METHOD" -H "Authorization: Bearer $TOKEN" \
                     -H "Accept: application/vnd.github+json" \
                     -H "X-GitHub-Api-Version: 2022-11-28" \
                     -d "$BODY" \
                     "$BASE_URL")
        BODY_PARSED=$(echo "$RESPONSE" | jq -c '.' | sed 's/"/\\"/g')
        echo "body=$BODY_PARSED" >> $GITHUB_OUTPUT
