# .github/actions/register_test_report/action.yml

name: Register test to report service
description: Register test to report service

inputs:
  title:
    description: "Title of the test"
    required: true
  subtitle:
    description: "Subtitle of the test"
    required: false
  github_token:
    description: "GitHub token"
    required: true
  extra_job_name:
    description: "Extra job name"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get Job ID
      shell: bash
      id: get_job_id
      run: |
        JOBS_RESPONSE=$(curl -s -H "Authorization: token ${{ inputs.github_token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs")

        JOB_NAME="${{ github.job }}"
        if [ -n "${{ inputs.extra_job_name }}" ]; then
          JOB_NAME="${JOB_NAME} (${{ inputs.extra_job_name }})"
        fi

        JOB_ID=$(echo "$JOBS_RESPONSE" | jq -r --arg job_name "$JOB_NAME" '.jobs[] | select(.name == $job_name) | .id')
        
        if [ -z "$JOB_ID" ]; then
          echo "Error: Could not find job ID for job name: $JOB_NAME"
          echo "JOBS_RESPONSE: $JOBS_RESPONSE"
          exit 1
        fi

        echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT

    - name: Register test to report service
      shell: bash
      run: |
        BASE_URL="https://report.rt.dnotitia.ai/github/test_job"
        METHOD="POST"
        RUN_ID="${{ github.run_id }}"
        JOB_ID="${{ steps.get_job_id.outputs.job_id }}"
        REPO_NAME="${{ github.repository }}"
        BRANCH="${{ github.ref_name }}"

        TITLE="${{ inputs.title }}"
        SUBTITLE="${{ inputs.subtitle }}"
        BODY="{\"run_id\": \"$RUN_ID\", \"job_id\": \"$JOB_ID\", \"repo_name\": \"$REPO_NAME\", \"head_branch\": \"$BRANCH\", \"title\": \"$TITLE\", \"subtitle\": \"$SUBTITLE\"}"

        RESPONSE=$(curl -X "$METHOD" -H "Content-Type: application/json" \
                  -d "$BODY" \
                  "$BASE_URL")
        echo "$RESPONSE"
